package collector

// AllCollectors returns all standard collectors to register with the server.
func AllCollectors() []Collector {
	return []Collector{
		NewHealthCollector(),
		NewSystemResourceCollector(),
		NewIdentityCollector(),
		NewInterfaceCollector(),
		NewMonitorCollector(),
		NewPOECollector(),
		NewDHCPCollector(),
		NewPoolCollector(),
		NewRouteCollector(),
		NewFirewallCollector(),
		NewAddressListCollector(),
		NewNeighborCollector(),
		NewNetwatchCollector(),
		NewPackageCollector(),
		NewUserCollector(),
		NewQueueCollector(),
		NewConnectionCollector(),
		NewPublicIPCollector(),
		NewSwitchPortCollector(),
		NewBFDCollector(),
		NewBGPCollector(),
		NewDNSCollector(),
		NewRoutingStatsCollector(),
		NewSystemUpdateCollector(),
		NewIPSecCollector(),
		NewCertificateCollector(),
		NewLTECollector(),
		NewWLANCollector(),
		NewCAPsMANCollector(),
		NewEOIPCollector(),
		NewGRECollector(),
		NewIPIPCollector(),
		NewKidControlCollector(),
		NewKidControlDeviceCollector(),
		NewContainerCollector(),
		NewMktxpCollector(),
		NewW60GCollector(),
		NewBandwidthCollector(),
	}
}
